# Generated by Django 3.2.5 on 2021-07-09 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/chats/%Y/%m', verbose_name='Изображение чата')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг чата')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель чата')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-created', 'updated'],
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('first_opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь')),
                ('second_opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-created', 'updated'],
                'unique_together': {('first_opponent', 'second_opponent')},
            },
        ),
        migrations.CreateModel(
            name='DialogMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000, verbose_name='Сообщение')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialog', to='chats.dialog', verbose_name='Диалог')),
                ('dialog_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialog_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created', 'updated'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000, verbose_name='Сообщение')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Chat', to='chats.chat', verbose_name='Чат')),
                ('chat_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created', 'updated'],
            },
        ),
    ]
