# Generated by Django 3.2.5 on 2021-07-09 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together={('first_opponent', 'second_opponent'), ('second_opponent', 'first_opponent')},
        ),
    ]
